{
 "title": "TP-Link Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Wattage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tplink_energy_power_watts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Relay State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "tplink_relay_state", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "tplink_energy_current", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Wattage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "tplink_energy_power_watts", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "tplink_energy_voltage", "legendFormat": "{{name}}" }
   ]
  }
 ]
}